version: '2'
services:
  mrover:
    image: mrover_build:0.3nolfs
    container_name: mrover_gui
    environment:
      - LIBGL_ALWAYS_SOFTWARE=1
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_X11_NO_MITSHM=1
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
    entrypoint: ["/home/mrover/ros2_ws/src/mrover/entrypoint.sh"]
    command: ["ros2", "launch", "mrover", "simulator.launch.py"]
    tty: true
    stdin_open: true
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=3456
      - DISPLAY_HEIGHT=2234
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11: