# All units are in SI
# ===================
# Time:     second, hz
# Angle:    radian
# Distance: meter

differential_drive_controller:
  ros__parameters:
    rover:
      width: 0.86
      length: 0.86
      wheel_radius: 0.13
      max_linear_speed: 1.0
      max_angular_speed: 3.0
